clear;
% Read 3 images. 
pepperImage = uint8(imread('peppers.tif'));
baboonImage = uint8(imread('baboon.tif'));
barImage = uint8(imread('Barbara.bmp'));

% Set an arbitary value as key. 
key = 1;
% Hide most significant bit plane of Barbara.bmp image into
% peppers.tif and baboon.tif
barMSBPlane = getBitPlane(barImage, 8);
pepperImageWMK = YMWaterMark(pepperImage, barMSBPlane, key);
figure, imshow(pepperImageWMK);
figure, imshow(getBitPlane(pepperImageWMK, 1));
% figure, imshow(extractYMmark(pepperImageWMK, key));
baboonImageWMK = YMWaterMark(baboonImage, barMSBPlane, key);
figure, imshow(baboonImageWMK);
figure, imshow(getBitPlane(baboonImageWMK, 1));

% Calculate PSNR of original images, LSB embedded images,
% and YM watermarked images.
pepperLSBWMK = embedBit(pepperImage, barImage, 1);
PSNRpepperYM = getPSNR(pepperImage, pepperImageWMK);
PSNRpepperLSB = getPSNR(pepperImage, pepperLSBWMK);
baboonLSBWMK = embedBit(baboonImage, barImage, 1);
PSNRbaboonYM = getPSNR(baboonImage, baboonImageWMK);
PSNRbaboonLSB = getPSNR(baboonImage, baboonLSBWMK);

% Use water mark extraction function to extract a image marked
% by look up table generated by key of 435. 
key = 435;
markedImage = uint8(imread('YMwmkedKey435.tiff'));
watermark435 = extractYMmark(markedImage, key);
figure, imshow(watermark435);

key = 1;
% Mix top half of marked baboon image with bottom half of pepper image.
mixedLSB = uint8(zeros(size(pepperImage)));
mixedYM = uint8(zeros(size(pepperImage)));
for i = 1 : floor(size(pepperImage, 1) / 2)
    offset = floor(size(pepperImage, 1) / 2);
    for j = 1 : size(pepperImage, 2)
        mixedLSB(i, j) = pepperImage(i + offset, j);
        mixedYM(i, j) = pepperImage(i + offset, j);
    end
end
for i = floor(size(baboonImage, 1) / 2) + 1 : size(baboonImage, 1)
    for j = 1 : size(baboonImage, 2)
        mixedLSB(i, j) = baboonLSBWMK(i, j);
        mixedYM(i, j) = baboonImageWMK(i, j);
    end
end
% Extract water marks from mixed images.
mixedLSBPlane = getBitPlane(mixedLSB, 1);
mixedYMmark = extractYMmark(mixedYM, key);
figure, imshow(mixedLSBPlane);
figure, imshow(mixedYMmark);
